---
title: "Untitled"
author: "Georgina Robertson"
date: "29/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

Reading in and formatting of the data
```{r}
chr1postLD <- read.delim("./LDfiles/post_chr13.ld", header = F)
# col names
colnames(chr1postLD) <- c("CHR",	"POS1", "POS2",	"N_CHR",	"Rsq",	"D",	"Dprime")
# new varible of distance
chr1postLD$distance <- chr1postLD$POS2 - chr1postLD$POS1
# peek
head(chr1postLD)
```
```{r}
chr1preLD <- read.delim("./LDfiles/pre_chr13.ld", header = F)
# col names
colnames(chr1preLD) <- c("CHR",	"POS1", "POS2",	"N_CHR",	"Rsq",	"D",	"Dprime")
# new varible of distance
chr1preLD$distance <- chr1preLD$POS2 - chr1preLD$POS1
# peek
head(chr1preLD)
```

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
```

```{r}
chr1postLD$distc <- cut(chr1postLD$distance, breaks = seq(from=min(chr1postLD$distance)-1, to=max(chr1postLD$distance)+1, by=100))

chr1postLD1 <- chr1postLD %>% group_by(distc) %>% summarise(mean=mean(Rsq), median=median(Rsq))

chr1postLD1 <- chr1postLD1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
```

```{r}
chr1preLD$distc <- cut(chr1preLD$distance, breaks = seq(from=min(chr1preLD$distance)-1, to=max(chr1preLD$distance)+1, by=100))

chr1preLD1 <- chr1preLD %>% group_by(distc) %>% summarise(mean=mean(Rsq), median=median(Rsq))

chr1preLD1 <- chr1preLD1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-e+.]+")), end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")), mid=start+((end-start)/2))
```

```{r}
ggplot()+
  geom_point(data = chr1postLD1, aes(x=start, y=mean), size=0.4, colour="grey20")+
  geom_line(data = chr1postLD1, aes(x=start,y=mean),size=0.5,alpha=0.5,colour="grey40")+
    geom_line(data = chr1preLD1, aes(x=start,y=mean),size=0.5,alpha=0.5,colour="red")+
  geom_smooth(data=chr1postLD1, aes(x=start,y=mean), method = "loess", formula=y~(x^2), colour="blue")+
  labs(x="Distance (bases x100)",y=expression(LD~(r^{2})))+
  # scale_x_continuous(breaks=c(0,2*10^6,4*10^6,6*10^6,8*10^6),labels=c("0","2","4","6","8"))+
  theme_bw()
```

```{r}
qplot(x=chr1postLD1$start, y=chr1postLD1, geom = "smooth", span=0.5)
```

