---
title: "Pre_IHS_plots"
author: "G.Robertson"
date: "26/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Plotting IHS of pre-drought populations


```{r}
library(stringr)
```

```{r}
preIHS <- read.csv("./data_sheets/ISH_Pre.csv")
preIHS$NegAbs <- -abs(preIHS$IHS)
preIHS<- preIHS[,-1]
preIHS <- na.omit(preIHS)


temp <- preIHS$CHR
temp2 <- str_split(temp, "_")
temp3 <- sapply(temp2, "[[", 3)
preIHS$CHR <- temp3

rm(temp, temp2, temp3)
```


```{r}
library(ggplot2)
```

```{r}
chr1pre <- preIHS[preIHS$CHR=="01",]
range(chr1pre$POSITION)

pre1 <- 
  ggplot(data = chr1pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
  ylab("-[iHS]")+   
  theme(plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr2pre <- preIHS[preIHS$CHR=="02",]

pre2 <- 
  ggplot(data = chr2pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
    theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr3pre <- preIHS[preIHS$CHR=="03",]

pre3 <- 
  ggplot(data = chr3pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
    theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr4pre <- preIHS[preIHS$CHR=="04",]

pre4 <- 
  ggplot(data = chr4pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
    theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr5pre <- preIHS[preIHS$CHR=="05",]

pre5 <- 
  ggplot(data = chr5pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
  theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr6pre <- preIHS[preIHS$CHR=="06",]

pre6 <- 
  ggplot(data = chr6pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr7pre <- preIHS[preIHS$CHR=="07",]


pre7 <- 
  ggplot(data = chr7pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr8pre <- preIHS[preIHS$CHR=="08",]

pre8 <- 
  ggplot(data = chr8pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr9pre <- preIHS[preIHS$CHR=="09",]

pre9 <- 
  ggplot(data = chr9pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr10pre <- preIHS[preIHS$CHR=="10",]

pre10 <- 
  ggplot(data = chr10pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr11pre <- preIHS[preIHS$CHR=="11",]

pre11 <- 
  ggplot(data = chr11pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr12pre <- preIHS[preIHS$CHR=="12",]

pre12 <- 
  ggplot(data = chr12pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```

```{r}
chr13pre <- preIHS[preIHS$CHR=="13",]

pre13 <- 
  ggplot(data = chr13pre, aes(x=POSITION/1000000, y=NegAbs))+
  geom_point(shape=20, colour="darkslategrey")+
  xlab("")+
   theme(axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 1,
                             l=0))
```


```{r}
library(cowplot)
```

```{r}
posrange <- c(range(chr1pre$POSITION), range(chr2pre$POSITION), range(chr3pre$POSITION), range(chr4pre$POSITION), range(chr5pre$POSITION), range(chr6pre$POSITION), range(chr7pre$POSITION), range(chr8pre$POSITION), range(chr9pre$POSITION), range(chr10pre$POSITION), range(chr11pre$POSITION), range(chr12pre$POSITION), range(chr13pre$POSITION))

print(posrange[seq(2, length(posrange), 2)])
```


```{r}
preplot2 <- plot_grid(pre1, pre2, pre3, pre4, pre5, pre6, pre7, pre8, pre9, pre10, pre11, pre12, pre13, ncol = 13, nrow = 1, rel_widths = c(6.3, 4.1, 3.9, 3, 3, 2.5, 2.9, 2.5, 2.1, 1.9, 1.7, 1.5, 1.2))
```

```{r}
ggsave(filename = "./IMGS/WG_ISH_pre.png", plot = preplot2, device = "png", width = 50, height = 4, units = "cm")
```

