---
title: "REHH"
author: "Georgina Robertson"
date: "15/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
library(rehh)
library(data.table)
```

```{r}
chr1PRE <- data2haplohh(hap_file = "./ByPop_Chrom/Chr_01.pre.recode.vcf", vcf_reader = "data.table", verbose = F, polarize_vcf = F)

chr1POST <- data2haplohh(hap_file = "./ByPop_Chrom/Chr_01.post.recode.vcf", vcf_reader = "data.table", verbose = F, polarize_vcf = F)
```

Cross population extended haplotype homozygosity (XP-EHH)
https://rdrr.io/cran/rehh/man/ies2xpehh.html
```{r}
scan_pop1 <- scan_hh(chr1POST)
scan_pop2 <- scan_hh(chr1PRE)
```

 Compute XP-EHH 
```{r}
chr1XP_EHH <- ies2xpehh(
  scan_pop1,
  scan_pop2,
  popname1 = "pre",
  popname2 = "post",
  min_nhaplo = NA,
  standardize = TRUE,
  include_freq = FALSE,
  p.side = NA,
  p.adjust.method = "none",
  verbose = TRUE
)
```
```{r}
write.csv(scan_pop1, file = "./REHH/chr16XPEHH.csv")
```

https://www.biostars.org/p/170385/
https://www.biostars.org/p/170385/
Going to try this in a loop

Store the file paths as variables
```{r}
filesPRE <- list.files(path ="./ByPop_Chrom/", pattern = "*.pre.recode.vcf", full.names = T, recursive = T)
filesPOST <- list.files(path ="./ByPop_Chrom/", pattern = "*.post.recode.vcf", full.names = T, recursive = T)

filesPRE <- as.data.frame(filesPRE)
filesPRE$chrom <- c(1:16, 19:21)
filesPOST <- as.data.frame(filesPOST)
filesPOST$chrom <- c(1:16, 19:21)
```

Loop through the files, perform the analysis for each pair, write to csv
```{r}
for (i in 1:19) {
  
  prepop  <- data2haplohh(hap_file = filesPRE$filesPRE[i],
                          vcf_reader = "data.table", verbose = F, polarize_vcf = F)
  postpop  <- data2haplohh(hap_file = filesPOST$filesPOST[i],
                          vcf_reader = "data.table", verbose = F, polarize_vcf = F)
  scan_pop1 <- scan_hh(prepop)
  scan_pop2 <- scan_hh(postpop)
  
  chrXP_EHH <- ies2xpehh(
    scan_pop1,
    scan_pop2,
    popname1 = "pre",
    popname2 = "post",
    min_nhaplo = NA,
    standardize = TRUE,
    include_freq = FALSE,
    p.side = NA,
    p.adjust.method = "none",
    verbose = TRUE
  )
  
  write.csv(chrXP_EHH, file = paste("./REHH/chr_", filesPOST$chrom[i], "XP_EHH.csv", sep = ""))
  
  rm(prepop, postpop, scan_pop1, scan_pop2, chrXP_EHH)
}
```

Only the core chromosomes had enough markers for the above process.


```{r}
files <- list.files(path ="./REHH/", pattern = "*_EHH.csv", full.names = T, recursive = T)

dflist <- lapply(files, function(i){
 df <- read.csv(i)
 return(df)
})
EHH_CoreChroms <- do.call(rbind, dflist)
EHH_CoreChroms <- EHH_CoreChroms[,-1]

write.csv(EHH_CoreChroms, file = "./REHH/core_withNA_EHH.csv")
# maybe remove NA's
EHH_CoreChroms_noNA <- na.omit(EHH_CoreChroms)
write.csv(EHH_CoreChroms_noNA, file = "./REHH/core_chroms_EHH.csv")
```

```{r}
unique(EHH_CoreChroms$CHR)

chromorder <- c("WAI332_chr_01","WAI332_chr_02","WAI332_chr_04","WAI332_chr_05","WAI332_chr_06","WAI332_chr_07","WAI332_chr_08","WAI332_chr_09","WAI332_chr_10", "WAI332_chr_11", "WAI332_chr_12", "WAI332_chr_13")
```

