---
title: "Merging SNP index and FST scores"
author: "Georgina Robertson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matching loci from FST output to SNP index as seen in heatmaps

Read in the individual loci files generated by the snp matrices (which were used to produce heatmaps) and merge them into one
```{r}
# set the path and pattern of the files 
files <- list.files(path ="./Processed_SNP_matrices/", pattern = "*loci.csv", full.names = T, recursive = T)

# read them all in while also setting colnames
dflist <- lapply(files, function(i){
 df <- read.csv(i, col.names = c("SNPindex", "Scaffold", "Position"))
 return(df)
})

# rbind them all together
snpindeces <- do.call(rbind, dflist)
```


```{r}
# merge the fst output and the above table by the common values: scaffold and Loci / position
FST_SnpIndex <- merge(snpindeces, fst_file, by=c("Position", "Scaffold"))
```

Save this to file!
```{r}
write.csv(FST_SnpIndex ,file="./data_sheets/FST_SNPindex.csv")
```

