---
title: "XPEHH_long_scatter"
author: "G.Robertson"
date: "13/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plots for Compositite FST and XP_EHH plots

### Run this first, then FST_long_scatte.Rmd

Load in the data
```{r}
XPEHHfile <- read.csv("./data_sheets/XPEHH_na.rm.csv")

```

Subset by chromosome and make custom plot for each one
```{r}
chr1 <- XPEHHfile[XPEHHfile$CHR==1, ]

x1 <- ggplot(data= chr1, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  xlab("Chromosome     1")+
  ylab(expression(log[10]~P-val))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr2 <- XPEHHfile[XPEHHfile$CHR==2, ]

x2 <- ggplot(data= chr2, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("2")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr3 <- XPEHHfile[XPEHHfile$CHR==3, ]

x3 <- ggplot(data= chr3, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("3")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr4 <- XPEHHfile[XPEHHfile$CHR==4, ]

x4 <- ggplot(data= chr4, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("4")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r}
chr5 <- XPEHHfile[XPEHHfile$CHR==5, ]

x5 <- ggplot(data= chr5, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("5")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r}
chr6 <- XPEHHfile[XPEHHfile$CHR==6, ]

x6 <- ggplot(data= chr6, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  xlab("6")+
  scale_x_continuous(breaks = c(0,1,2))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r}
chr7 <- XPEHHfile[XPEHHfile$CHR==7, ]

x7 <- ggplot(data= chr7, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("7")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r}
chr8 <- XPEHHfile[XPEHHfile$CHR==8, ]

x8 <- ggplot(data= chr8, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("8")+
  scale_x_continuous(breaks = c(0,1,2))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr9 <- XPEHHfile[XPEHHfile$CHR==9, ]

x9 <- ggplot(data= chr9, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("9")+
  scale_x_continuous(breaks = c(0,1,2))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr10 <- XPEHHfile[XPEHHfile$CHR==10, ]

x10 <- ggplot(data= chr10, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("10")+
  scale_x_continuous(breaks = c(0,1,2))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr11 <- XPEHHfile[XPEHHfile$CHR==11, ]

x11 <- ggplot(data= chr11, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  xlab("11")+
  scale_x_continuous(breaks = c(0,1))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr12 <- XPEHHfile[XPEHHfile$CHR==12, ]

x12 <- ggplot(data= chr12, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  xlab("12")+
  scale_x_continuous(breaks = c(0,1))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
chr13 <- XPEHHfile[XPEHHfile$CHR==13, ]

x13 <- ggplot(data= chr13, aes(x=POSITION/1000000, y=LOGPVALUE))+
 geom_line( colour="firebrick4")+
  

  xlab("13")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          plot.margin = margin(t=1,
                             r=0.25,
                             b= 0.25,
                             l=0))+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
